# This is a basic workflow to help you get started with Actions

name: 'refresh'

# Controls when the action will run. 
on:
  schedule:
    - cron: '10 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: OS dependencies
        run: |
          apt update
          apt install chromium-chromedriver
      - name: Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      # Runs a set of commands using the runners shell
      - name: Refresh data
        run: |
          echo "finish"
          java --version
          
